USE [NBADB]
GO

/****** Object:  Table [dbo].[tblDivision]    Script Date: 4/19/2017 12:54:56 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[tblDivision](
	[dvID] [int] NOT NULL,
	[dvName] [varchar](15) NOT NULL,
	[dvConference] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[dvID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[tblDivision]  WITH CHECK ADD FOREIGN KEY([dvConference])
REFERENCES [dbo].[tblConference] ([cfID])
GO
