USE [NBADB]
GO

/****** Object:  Table [dbo].[tblPosition]    Script Date: 4/24/2017 1:18:04 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[tblPosition](
	[poID] [int] NOT NULL,
	[poDesc] [varchar](20) NULL,
	[poShortDesc] [varchar](2) NULL,
PRIMARY KEY CLUSTERED 
(
	[poID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
